export const questions = [
	'What services does KISS Agency offer?',
	'What platforms does KISS Agency support for web development and design?',
	'What specializations does KISS Agency have in web development?',
	'What SEO and website optimization services does KISS Agency provide?',
	'What hosting and website management services are available at KISS Agency?',
	'What APIs does KISS Agency have expertise with?',
	'What kind of app development does KISS Agency offer?',
	'What AI solutions can KISS Agency provide for my business?',
	'Which industries does KISS Agency serve?',
	'Who leads the team at KISS Agency and what are their specialties?',
	'What roles and expertise do the team members at KISS Agency have?',
	"What makes KISS Agency's approach to AI integration unique?",
	'What is the process KISS Agency follows for AI integration?',
	'Can you give examples of AI-driven projects KISS Agency has completed?',
	'How does KISS Agency ensure quality and consistency in its projects?',
	'What is the initial consultation process at KISS Agency like?',
	'How does KISS Agency conduct research and analysis for AI integration?',
	'How does KISS Agency develop and plan AI strategies?',
	'What is involved in platform building and integration at KISS Agency?',
	'How does KISS Agency train and optimize AI models?',
	'What is the deployment and monitoring process for AI solutions at KISS Agency?',
	'How does KISS Agency ensure continuous improvement in AI solutions?',
	'How can I contact KISS Agency to explore AI integration for my business?',
	'What are the benefits of working with KISS Agency for digital marketing and AI solutions?',
];
